# This serves to set the port for local development
services:
  nginx:
    ports:
      - "8080:80"
    volumes:
      - type: bind
        source: src/nginx/nginx.dev.mac.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
        bind:
          selinux: Z
  backend:
    build:
      target: base
    environment:
      SESSION_COOKIE_SECURE: ${SESSION_COOKIE_SECURE:-false}
