server {
  listen 80;
  absolute_redirect off;

  location /api/images {
    alias /gallery/; # gallery directory which should be mounted into the nginx container
    autoindex on;
    autoindex_format json;

    # `sendfile` lets Nginx send static files directly from the kernel to the network socket, reducing CPU usage and unnecessary data copying.
    sendfile on;
  }

  # Backend (FastAPI)
  location /api/ {
    proxy_pass http://backend:8000/; # Strips Prefix

    # Preserve the original request host, client IP, proxy chain, and protocol so the backend
    # can correctly handle logging, redirects, authentication, rate limiting, and URL generation.
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  # Frontend (Next.js)
  location / {
        proxy_pass http://frontend:3000/; # Strips Prefix

        # Preserve the original request host, client IP, proxy chain, and protocol so the backend
        # can correctly handle logging, redirects, authentication, rate limiting, and URL generation.
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
  }
}